student_marks = []
m1 = float(input("Ente the marks: "))
student_marks.append(m1)
m2 = float(input("Ente the marks: "))
student_marks.append(m2)
m3 = float(input("Ente the marks: "))
student_marks.append(m3)
m4 = float(input("Ente the marks: "))
student_marks.append(m4)
m5 = float(input("Ente the marks: "))
student_marks.append(m5)
m6 = float(input("Ente the marks: "))
student_marks.append(m6)
student_marks.sort()
print(student_marks)