a = set()
print(type(a))
s1 = int(input("enter the num:"))
a.add(s1)
s2 = int(input("enter the num:"))
a.add(s2)
s3 = int(input("enter the num:"))
a.add(s3)
s4 = int(input("enter the num:"))
a.add(s4)
s5 = int(input("enter the num:"))
a.add(s5)
s6 = int(input("enter the num:"))
a.add(s6)
s7 = int(input("enter the num:"))
a.add(s7)
s8 = int(input("enter the num:"))
a.add(s8)
print(a)